// SignUp Constant
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// verify Success
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

// SignIn
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

// Logout
export const LOGOUT_USER = 'LOGOUT_USER'

// Product List
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

// Product Add
export const PRODUCT_ADD_REQUEST='PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS='PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL='PRODUCT_ADD_FAIL';

// Product Edit
export const PRODUCT_EDIT_REQUEST='PRODUCT_EDIT_REQUEST';
export const PRODUCT_EDIT_SUCCESS='PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL='PRODUCT_EDIT_FAIL';

// Product Update
export const PRODUCT_UPDATE_REQUEST='PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS='PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL='PRODUCT_UPDATE_FAIL';

// Product Delete
export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL='PRODUCT_DELETE_FAIL';

// Order LIst
export const ORDER_LIST_REQUEST='ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS='ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL='ORDER_LIST_FAIL';
